export const commetns = document.querySelector(".comments-js")
export const form = document.querySelector(".form-js")
export const name = document.querySelector(".name-js")
export const content = document.querySelector(".content-js")
export const closeCookies = document.querySelector(".cookieClose")
export const cookiesBar = document.querySelector(".cookiesBar")